### ISSUE TITLE
Setup github actions .

### ISSUE THREAD

**Issue by nlok5923** [iiitv/iiitvcc#10]
currently their's no github action for install and build .
@iiitv/project-maintainers  if this issue is valid i would like to work on it .

**Comment by aashutoshrathi** [comment]
GitHub action for what purpose exactly?

**Comment by nlok5923** [comment]
Sir for install and build.

**Comment by aashutoshrathi** [comment]
Why install and build? what next?

**Comment by nlok5923** [comment]
Sir I thought that it will help to detect whether project works fine with this pr of not. Sir if we can add more please tell me I am eager to learn that.

**Comment by aashutoshrathi** [comment]
Just read about "How and What Actions or CI/CD are used for", we shouldn't aimlessly add them to projects.

**Comment by nlok5923** [comment]
Okay sir.
