### ISSUE TITLE
Profile Button Overlaps Menu Button on Mobile View After Sign-in

### ISSUE THREAD

**Issue by Anas-github-acc** [iiitv/iiitvcc#114]
<h2>Description:</h2>
When signing into the mobile version of the site, the profile button appears and overlaps the menu button. This causes the menu to become inaccessible, as the profile button obstructs the touch area.

<h2>Steps to Reproduce:</h2>

1. Go to the website on a mobile device or use mobile view in the browser.
2. Click on the menu button to verify it's functioning.
3. Sign in to the account.
4. Observe that the profile button appears and overlaps with the menu button.

<h2>Expected Behavior:</h2>
The menu button and the profile button should be positioned horizontally such that they don't overlap after sign-in, ensuring both are accessible and profile button should be right of menu button.

<h2>Screenshots:</h2>

![Screenshot 2024-10-01 131921](https://github.com/user-attachments/assets/6d5be5e9-3f93-4a40-aad8-d8b0e5c7bfb5)

<h2>Possible Solution:</h2>

- Adjust CSS to reposition the profile button when it's displayed to avoid overlapping with the menu button.

**Comment by deveshsawant05** [comment]
Assign me this issue.
