### ISSUE TITLE
 Implement Contact Page Email Functionality

### ISSUE THREAD

**Issue by Anas-github-acc** [iiitv/iiitvcc#117]
Implement Contact Page Email Functionality
---

*Description:*  
Currently, the contact page is implemented but does not have functionality for sending emails. The objective is to add functionality so that when the form is submitted, the user's message is sent to the Coding Club's official email address (codingclub@iiitvadodara.ac.in).

*Tasks:*
- [ ] Implement backend functionality to handle form submission (using an email service like Nodemailer, or an API such as SendGrid).
- [ ] Ensure all fields (Name, Email, Contact No., Organisation, Message/Bug) are included in the email body.
- [ ] Display a confirmation message on successful submission (already present).
- [ ] Handle error cases (e.g., email sending failure) and display appropriate feedback to the user.

*Acceptance Criteria:*
- The form should successfully send the message to the Coding Club's official email address when submitted.

*Additional Notes:*
- Coding Club Email: codingclub@iiitvadodara.ac.in
- Preferred Email Service: [Insert service like Nodemailer/SendGrid if preferred].

---

This issue provides clear steps for adding functionality and validation for the contact form on your website.

**Comment by deveshsawant05** [comment]
Assign me this Issue.
