### ISSUE TITLE
Redesign Events Page

### ISSUE THREAD

**Issue by Anas-github-acc** [iiitv/iiitvcc#118]
## Title: Redesign Events Page to Align with Website Theme

**Description:**
The events page needs a redesign to enhance user experience and ensure it follows the overall theme of our website.

**Requirements:**
- Redesign the events page layout to match the existing website theme (colors, typography, and spacing, header, footer).
- Improve the presentation of event details, including the poster, description, date, and host link.
- Maintain responsiveness across devices, ensuring a seamless experience on both mobile and desktop.
- Ensure that the "Show More" button integrates visually with the new design while functioning smoothly to load additional events.

**Acceptance Criteria:**
- The new design should be implemented as a separate branch for review.
- The layout must be visually consistent with the rest of the website and fully responsive.
- Provide mockups or wireframes for feedback before implementation.
- Ensure the event fetching functionality remains intact and optimized for performance.

**Comment by deveshsawant05** [comment]
Assign me this issue.
