### ISSUE TITLE
Add Navbar and Footer to Event/[id] page

### ISSUE THREAD

**Issue by Anas-github-acc** [iiitv/iiitvcc#124]
**Description**
The `Event/[id]` page currently lacks a Navbar and Footer. The components for both the Navbar and Footer are already created and can be found in the `src/components` folder.

**Tasks**
- Import the Navbar and Footer components to `Event/[id]` page.
- Integrate the Navbar at the top and Footer at the bottom of the Event/[id] page.
- Ensure styling and responsiveness are consistent with the rest of the site.

**Comment by Virtual4087** [comment]
Hey @Anas-github-acc I would love to do this. Can to assign this to me?

**Comment by Anas-github-acc** [comment]
hey Virtual4087!, awesome that you want to work on the issue! a quick note - use the `new` branch for all your work, as that’s our primary branch for active development (not the default). You can check the current setup here for reference: [(https://github.com/iiitv/iiitvcc/tree/new)](https://github.com/iiitv/iiitvcc/tree/new).
hit me up if you need anything

**Comment by deveshsawant05** [comment]
Assign me this issue
