### ISSUE TITLE
Fetch and Display Upcoming Events on Homepage

### ISSUE THREAD

**Issue by Anas-github-acc** [iiitv/iiitvcc#126]
### Issue: Fetch and Display Events by Category on Homepage with Toggle Buttons

**Description**
The homepage currently has a hardcoded "Upcoming Events" section. Update this section to dynamically fetch and display events by category. Implement toggle buttons to switch between "Upcoming," "Past," and "Ongoing" events, with "Upcoming" as the default. The section should display only 3 events at a time based on the selected category.

**Tasks**
**Add Toggle Buttons**
- Create 3 buttons labeled "upcoming" (default), "past," and "ongoing."
- Use these buttons to let users toggle between the event categories on the homepage.

**Fetch Events Based on Category**
- On toggle, make an API call to `api/v1/get/events?category=''` with the selected category as a query parameter (e.g., `?category='upcoming'`).
- you have 3 category `upcoming, past, ongoing`
- Fetch and display only 3 events at a time based on the selected category.

**Update UI for Event Display**
- Replace hardcoded event data with dynamically fetched data.
- Display key information for each event, such as title short description , date, time, mode and image (optional).
- Ensure smooth transitions when switching between categories.

**Acceptance Criteria**
- The "Upcoming Events" section on the homepage displays events based on the selected category (`upcoming, past, or ongoing`).
- Display 3 events at a time, but you may show 4 if necessary
- Toggle buttons allow users to switch between event categories seamlessly.
- Error handling works properly, displaying a message if no events are available or if the API call fails.

**Comment by deveshsawant05** [comment]
Assign me this issue
