### ISSUE TITLE
Implement Events page

### ISSUE THREAD

**Issue by AmanRaj1608** [iiitv/iiitvcc#14]
Anyone up for this?
Complete the event page UI design (responsive ofc). 

Design page -> 
- [Event page](https://www.figma.com/proto/5aLa8I7PiRdc25UrB1cL3e/CC-BLOG-Website?node-id=388%3A80&scaling=min-zoom)   
- [All designs](https://www.figma.com/proto/5aLa8I7PiRdc25UrB1cL3e/CC-BLOG-Website?node-id=388%3A80&scaling=min-zoom)

[Event.jsx](https://github.com/iiitv/iiitvcc/blob/master/pages/events.js)
[Event.css](https://github.com/iiitv/iiitvcc/blob/master/styles/Events.css)

**Comment by Im-Madhur-Gupta** [comment]
Hello, I would like to work on this issue.

**Comment by ShivanshKumar** [comment]
Sure, assigning you
