### ISSUE TITLE
Create Cover Page

### ISSUE THREAD

**Issue by AmanRaj1608** [iiitv/iiitvcc#2]
As per the design, this is our Cover Page. 

Implement this

![image](https://user-images.githubusercontent.com/42104907/86944745-cb023a80-c165-11ea-95f9-92b79eb2deaf.png)

**Comment by prathmeshkhandelwal1** [comment]
where can we find assets for this?

**Comment by prathmeshkhandelwal1** [comment]
and also i want to work on this.

**Comment by AmanRaj1608** [comment]
Sure @prathmeshkhandelwal1 
We are waiting for final designs. As soon as I get the designs I will let you know.

**Comment by prathmeshkhandelwal1** [comment]
okk

**Comment by AmanRaj1608** [comment]
@prathmeshkhandelwal1 mailed you the illustration

**Comment by nlok5923** [comment]
is this issue still open
@iiitv/project-maintainers i would like to work on it.

**Comment by AmanRaj1608** [comment]
Sure @nlok5923 GFI 👍🏻

**Comment by nlok5923** [comment]
@AmanRaj1608 sir do i have to make this page responsive
