### ISSUE TITLE
Implement responsive Members page

### ISSUE THREAD

**Issue by AmanRaj1608** [iiitv/iiitvcc#3]
![image](https://user-images.githubusercontent.com/42104907/87855651-51bdd100-c937-11ea-8210-e5f9e8e20b40.png)

Page with members cards. And there will be sections like Leaders, Members.

https://www.figma.com/proto/5aLa8I7PiRdc25UrB1cL3e/CC-BLOG-Website?node-id=605%3A2&scaling=min-zoom

**Comment by AmanRaj1608** [comment]
@Pranshu2780 

Can you do this?

**Comment by Pranshu2780** [comment]
YES, I will

**Comment by nlok5923** [comment]
is this issue still open 
@iiitv/project-maintainers i would like to work on it.

**Comment by nlok5923** [comment]
if this issue is still open @iiitv/project-maintainers i would like to work on it .

**Comment by AmanRaj1608** [comment]
@Pranshu2780 is working on this 😅
