### ISSUE TITLE
Updating members.json 

### ISSUE THREAD

**Issue by satyacasm** [iiitv/iiitvcc#33]
members.json file needs to be updated

@iiitv/project-maintainers Request you to assign this issue to me.

**Comment by AkhileshManda** [comment]
@Im-Madhur-Gupta

**Comment by Im-Madhur-Gupta** [comment]
@satyacasm GFI!

**Comment by madhukaraman** [comment]
Hey is this still available ?

**Comment by AkhileshManda** [comment]
Hey @madhukaraman! Thank you for your interest but the issue has been assigned to someone else and I think there is a PR ready already. I request you to look at other repos as well we have plenty of repos to contribute to.
