### ISSUE TITLE
make contact page 

### ISSUE THREAD

**Issue by ShravaniAK** [iiitv/iiitvcc#35]

**Comment by ShravaniAK** [comment]
@Im-Madhur-Gupta sir please assign me this issue

**Comment by AkhileshManda** [comment]
Do you wish to make a complete new page for IIITVCC Socials? I think the footer does the job

**Comment by ShravaniAK** [comment]
i wanted to make make a contact us page similar to this , will it be fine?
<img width="1440" alt="Screenshot 2022-10-03 at 12 10 58 PM" src="https://user-images.githubusercontent.com/97099574/193515541-609c7ea6-232f-4ad4-a8dc-e02aeb4c0e83.png">

**Comment by ShravaniAK** [comment]
om clicking contact us in navbar , home page is opening

**Comment by AkhileshManda** [comment]
GFI @ShravaniAK
