### ISSUE TITLE
Add .editorconfig  to the project. 

### ISSUE THREAD

**Issue by nlok5923** [iiitv/iiitvcc#8]
it would be really good if this project has it's own editor config file so that there should be a uniform indentation in the code.

**Comment by nlok5923** [comment]
if this issue is valid @iiitv/project-maintainers i would like to work on this issue.

**Comment by aashutoshrathi** [comment]
@nlok5923 GFI

**Comment by nlok5923** [comment]
@AmanRaj1608 sir can you please apply the contributathon label to this issue so that it can be counted as a valid issue.
